[connections.supabase]
SUPABASE_URL = "https://dzofltykejiqejikaber.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6b2ZsdHlrZWppcWVqaWthYmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTE2MDEsImV4cCI6MjA1NzU4NzYwMX0.Nb4JBhIbMQnCfEneVFjZRvQj9FKsEZbrQVHhHIA7Oo8"
